### ISSUE TITLE
Disconnect error when attacking

### ISSUE THREAD

**Issue by DerRedstoner** [CraftG/Horizon#10]
Please describe the problem in detail and provide as much information as possible.

Everytime I attack an entity in game, the account gets immediately disconnected from the server. I also reset the plugin completely and tried again. Everytime a disconnect. And the only thing that shows up is the error message below in console.

INFOMATION:
Server: Spigot
Server version: 1.12.2 

bypass/false positive/bug/error/suggestion
ISSUE TYPE: error

If reporting a console error.
SERVER LOG: derredstoner lost connection: Internal Exception: java.lang.NullPointerException

If reporting a false positive.
HORIZON LOG: -

If reporting a false positive/bypass. (If possible)
VIDEO: -

If reporting a bypass.
CLIENT: -

**Comment by CraftG** [comment]
I will fix it. You can temporarily disable the ForceField check.
