### ISSUE TITLE
[False Positive] Optifine Zoom

### ISSUE THREAD

**Issue by zHelp** [CraftG/Horizon#101]
Please describe the problem in detail and provide as much information as possible.

Horizon Version:  1.4.6

Server Core:  BeerSpigot

Server version:  1.8.8

Video:  N/A

Additional Info: 
False flag KillAura when you either use Optifine zoom or Cinematic Camera.

**Comment by coolpvpv1** [comment]
> Please describe the problem in detail and provide as much information as possible.
> 
> Horizon Version: 1.4.6
> 
> Server Core: BeerSpigot
> 
> Server version: 1.8.8
> 
> Video: N/A
> 
> Additional Info:
> False flag KillAura when you either use Optifine zoom or Cinematic Camera.

uh can you do a video if it

**Comment by CraftG** [comment]
Sorry, this can't be fixed.
