### ISSUE TITLE
[Bypass] LiquidWalk

### ISSUE THREAD

**Issue by zHelp** [CraftG/Horizon#102]
Please describe the problem in detail and provide as much information as possible.

Horizon Version:  1.4.6

Server Core:  BeerSpigot

Server version:  1.8.8

Video:  N/A

Client Info:  Depression v1.44

Additional Info:  
Check "Jesus": Jesus Bhop bypasses

**Comment by coolpvpv1** [comment]
> Please describe the problem in detail and provide as much information as possible.
> 
> Horizon Version: 1.4.6
> 
> Server Core: BeerSpigot
> 
> Server version: 1.8.8
> 
> Video: N/A
> 
> Client Info: Depression v1.44
> 
> Additional Info:
> Check "Jesus": Jesus Bhop bypasses

download to the client is https://depressionclient.club if anyone needs it

**Comment by CraftG** [comment]
Join our discord to get the latest dev build.
