### ISSUE TITLE
[False Positive] End Rod NOFALL and FLY causing players to fall through the end rod.

### ISSUE THREAD

**Issue by Busted11290** [CraftG/Horizon#104]
Please describe the problem in detail and provide as much information as possible.

**Horizon Version:** 1.4.6-Hotfix#8

**Server Core:**  Paper 187

**Server version:** 1.14.4

**Video:**  https://youtu.be/ePV_SoA9RyU

**Additional Info:**  Movement on End Rods cause players to fall through them and triggers verbose NOFALL and FLY checks.  This is an issue as it can kill a player if the rod is high enough.

Edit:
- Chorus plants do this as well.

**Comment by CraftG** [comment]
Join our discord to get the latest dev build.
