### ISSUE TITLE
[False Positive]  SPEED & FLY  Berry Bush

### ISSUE THREAD

**Issue by Busted11290** [CraftG/Horizon#105]
Jump on a berry bush for FLY and jump while standing in a berry bush for SPEED.

**Horizon Version:** 1.4.6-Hotfix#8

**Server Core:** Paper 192

**Server version:** 1.14.4

Video: 

Additional Info: 
17.09 02:06:38 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Expect d:-0.3857470913379615 e:-0.5143294189909678 VL:25.355026245117188 (+2.0) Ping:51
17.09 02:06:42 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Expect d:-0.3857470913379615 e:-0.5143294189909678 VL:24.199016571044922 (+2.0) Ping:51
17.09 02:06:44 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Equality d:-0.0588000011444052 VL:26.327014923095703 (+3.0) Ping:51
17.09 02:06:44 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Equality d:-0.0588000011444052 VL:29.247087478637695 (+3.0) Ping:51
17.09 02:06:46 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Expect d:-0.22615104274709097 e:-0.30153471235514956 VL:29.315654754638672 (+2.0) Ping:51
17.09 02:06:48 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Expect d:-0.0588000011444052 e:-0.22768848199505057 VL:29.394763946533203 (+2.0) Ping:53
17.09 02:06:52 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Expect d:-0.11642400338745063 e:-0.15523199999999998 VL:30.116268157958984 (+2.0) Ping:53
17.09 02:06:55 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Expect d:-0.11642400338745063 e:-0.15523199999999998 VL:30.82840347290039 (+2.0) Ping:53
17.09 02:06:59 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Equality d:-0.0588000011444052 VL:31.844287872314453 (+3.0) Ping:53
17.09 02:06:59 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Equality d:-0.0588000011444052 VL:34.74514389038086 (+3.0) Ping:53
17.09 02:06:59 [Server] INFO Horizon >> Player Decarubus failed SPEED Module:Expect p:0.0 d:0.3149999901652336 VL:2.05905818939209 (+2.0) Ping:53
17.09 02:06:59 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Equality d:-0.0588000011444052 VL:37.44633865356445 (+3.0) Ping:53
17.09 02:06:59 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Equality d:-0.0588000011444052 VL:40.44633865356445 (+3.0) Ping:53
17.09 02:07:00 [Server] INFO Horizon >> Player Decarubus failed SPEED Module:Expect p:0.0 d:0.3149999901652336 VL:3.919173240661621 (+2.0) Ping:53
17.09 02:07:00 [Server] INFO Horizon >> Player Decarubus failed SPEED Module:FastFall d:-0.0588000011444052 e:0.23029999659657463 VL:6.841183662414551 (+3.0) Ping:53
17.09 02:07:00 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Equality d:-0.0588000011444052 VL:43.034080505371094 (+3.0) Ping:53
17.09 02:07:00 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Equality d:-0.0588000011444052 VL:46.034080505371094 (+3.0) Ping:53
17.09 02:07:00 [Server] INFO Horizon >> Player Decarubus failed SPEED Module:Expect p:0.0 d:0.3149999901652336 VL:8.652933120727539 (+2.0) Ping:53
17.09 02:07:00 [Server] INFO Horizon >> Player Decarubus failed SPEED Module:FastFall d:-0.0588000011444052 e:0.23029999659657463 VL:11.54044246673584 (+3.0) Ping:53
17.09 02:07:00 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Equality d:-0.0588000011444052 VL:48.51062774658203 (+3.0) Ping:53
17.09 02:07:01 [Server] INFO Horizon >> Player Decarubus failed SPEED Module:Expect p:0.0 d:0.3149999901652336 VL:13.322132110595703 (+2.0) Ping:53
17.09 02:07:01 [Server] INFO Horizon >> Player Decarubus failed SPEED Module:Expect p:0.0 d:0.3149999901652336 VL:15.033615112304688 (+2.0) Ping:53
17.09 02:07:02 [Server] INFO Horizon >> Player Decarubus failed SPEED Module:Expect p:0.0 d:0.3149999901652336 VL:16.67765998840332 (+2.0) Ping:53
17.09 02:07:02 [Server] INFO Horizon >> Player Decarubus failed SPEED Module:Expect p:0.0 d:0.3149999901652336 VL:18.256921768188477 (+2.0) Ping:52
17.09 02:07:03 [Server] INFO Horizon >> Player Decarubus failed SPEED Module:Expect p:0.0 d:0.3149999901652336 VL:19.773954391479492 (+2.0) Ping:52

**Players also having issues with:** End Rods, Chorus Plants, and Scaffolding

**Comment by coolpvpv1** [comment]
> Jump on a berry bush for FLY and jump while standing in a berry bush for SPEED.
> 
> **Horizon Version:** 1.4.6-Hotfix#8
> 
> **Server Core:** Paper 192
> 
> **Server version:** 1.14.4
> 
> Video:
> 
> Additional Info:
> 17.09 02:06:38 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Expect d:-0.3857470913379615 e:-0.5143294189909678 VL:25.355026245117188 (+2.0) Ping:51
> 17.09 02:06:42 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Expect d:-0.3857470913379615 e:-0.5143294189909678 VL:24.199016571044922 (+2.0) Ping:51
> 17.09 02:06:44 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Equality d:-0.0588000011444052 VL:26.327014923095703 (+3.0) Ping:51
> 17.09 02:06:44 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Equality d:-0.0588000011444052 VL:29.247087478637695 (+3.0) Ping:51
> 17.09 02:06:46 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Expect d:-0.22615104274709097 e:-0.30153471235514956 VL:29.315654754638672 (+2.0) Ping:51
> 17.09 02:06:48 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Expect d:-0.0588000011444052 e:-0.22768848199505057 VL:29.394763946533203 (+2.0) Ping:53
> 17.09 02:06:52 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Expect d:-0.11642400338745063 e:-0.15523199999999998 VL:30.116268157958984 (+2.0) Ping:53
> 17.09 02:06:55 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Expect d:-0.11642400338745063 e:-0.15523199999999998 VL:30.82840347290039 (+2.0) Ping:53
> 17.09 02:06:59 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Equality d:-0.0588000011444052 VL:31.844287872314453 (+3.0) Ping:53
> 17.09 02:06:59 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Equality d:-0.0588000011444052 VL:34.74514389038086 (+3.0) Ping:53
> 17.09 02:06:59 [Server] INFO Horizon >> Player Decarubus failed SPEED Module:Expect p:0.0 d:0.3149999901652336 VL:2.05905818939209 (+2.0) Ping:53
> 17.09 02:06:59 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Equality d:-0.0588000011444052 VL:37.44633865356445 (+3.0) Ping:53
> 17.09 02:06:59 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Equality d:-0.0588000011444052 VL:40.44633865356445 (+3.0) Ping:53
> 17.09 02:07:00 [Server] INFO Horizon >> Player Decarubus failed SPEED Module:Expect p:0.0 d:0.3149999901652336 VL:3.919173240661621 (+2.0) Ping:53
> 17.09 02:07:00 [Server] INFO Horizon >> Player Decarubus failed SPEED Module:FastFall d:-0.0588000011444052 e:0.23029999659657463 VL:6.841183662414551 (+3.0) Ping:53
> 17.09 02:07:00 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Equality d:-0.0588000011444052 VL:43.034080505371094 (+3.0) Ping:53
> 17.09 02:07:00 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Equality d:-0.0588000011444052 VL:46.034080505371094 (+3.0) Ping:53
> 17.09 02:07:00 [Server] INFO Horizon >> Player Decarubus failed SPEED Module:Expect p:0.0 d:0.3149999901652336 VL:8.652933120727539 (+2.0) Ping:53
> 17.09 02:07:00 [Server] INFO Horizon >> Player Decarubus failed SPEED Module:FastFall d:-0.0588000011444052 e:0.23029999659657463 VL:11.54044246673584 (+3.0) Ping:53
> 17.09 02:07:00 [Server] INFO Horizon >> Player Decarubus failed FLY Module:Equality d:-0.0588000011444052 VL:48.51062774658203 (+3.0) Ping:53
> 17.09 02:07:01 [Server] INFO Horizon >> Player Decarubus failed SPEED Module:Expect p:0.0 d:0.3149999901652336 VL:13.322132110595703 (+2.0) Ping:53
> 17.09 02:07:01 [Server] INFO Horizon >> Player Decarubus failed SPEED Module:Expect p:0.0 d:0.3149999901652336 VL:15.033615112304688 (+2.0) Ping:53
> 17.09 02:07:02 [Server] INFO Horizon >> Player Decarubus failed SPEED Module:Expect p:0.0 d:0.3149999901652336 VL:16.67765998840332 (+2.0) Ping:53
> 17.09 02:07:02 [Server] INFO Horizon >> Player Decarubus failed SPEED Module:Expect p:0.0 d:0.3149999901652336 VL:18.256921768188477 (+2.0) Ping:52
> 17.09 02:07:03 [Server] INFO Horizon >> Player Decarubus failed SPEED Module:Expect p:0.0 d:0.3149999901652336 VL:19.773954391479492 (+2.0) Ping:52
> 
> **Players also having issues with:** End Rods, Chorus Plants, and Scaffolding

same issue as mine lol https://github.com/CraftG/Horizon/issues/99
