### ISSUE TITLE
[Error] IndexOutOfBoundsException

### ISSUE THREAD

**Issue by En0tS** [CraftG/Horizon#106]
Please describe the problem in detail and provide as much information as possible.

Horizon Version: 
1.4.6-Hotfix#8
Server Core: 
paper
Server version: 
build-1618(final 1.12.2 build)
Server Log: 
https://pastebin.com/iTP2PhuV
Additional Info:

**Comment by CraftG** [comment]
Join our discord to get the latest dev build.
