### ISSUE TITLE
[False Positive] FLY - Stuck in cobweb

### ISSUE THREAD

**Issue by Nety01** [CraftG/Horizon#108]
Please describe the problem in detail and provide as much information as possible.

Horizon Version: Horizon 1.4.6-Hotfix#8

Server Core: Paper 647

Server version: 1.13.2

Video: https://imgur.com/b0Hxriw

Additional Info: When you jump into a cobweb, sometimes you get stuck there and it gets the FLY false positive.

**Comment by CraftG** [comment]
Fixed in dev build.
