### ISSUE TITLE
[False Positive] Sink underwater and get stuck

### ISSUE THREAD

**Issue by Nety01** [CraftG/Horizon#109]
Please describe the problem in detail and provide as much information as possible.

Horizon Version: Horizon 1.4.6-Hotfix#8

Server Core: Paper 647

Server version: 1.13.2

Video: https://youtu.be/vQnwRKIRiAI

Additional Info: When you're swimming, sometimes you get sinked down and get stuck there.

**Comment by CraftG** [comment]
Fixed in dev build.
