### ISSUE TITLE
[Error] 1.14.4 when use /reload confirm it has benn WARN

### ISSUE THREAD

**Issue by roughanddai** [CraftG/Horizon#111]
Please describe the problem in detail and provide as much information as possible.

Horizon Version: Horizon 1.4.6-Hotfix#8

Server Core: paper-build209

Server version: 1.14.4

Server Log: https://pastebin.com/sGsPe2xq

Additional Info: using ProtocolLib build17 and using PlaceholderAPI 2.10.4
server start code -Xms5G -Xmx5G -XX:+UseLargePagesInMetaspace -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Dusing.aikars.flags=mcflags.emc.gs

**Comment by CraftG** [comment]
Sorry, Horizon does not support /reload, please fully restart the server.
