### ISSUE TITLE
[Error] When swam in lava

### ISSUE THREAD

**Issue by roughanddai** [CraftG/Horizon#114]
Please describe the problem in detail and provide as much information as possible.

Horizon Version: Horizon-1.4.6-Hotfix#8

Server Core: Paper version git-Paper-221

Server version: 1.14.4

Server Log: https://pastebin.com/Vg5mbVfn

Additional Info: using
PlaceholderAPI-2.10.4
ProtocolLib v4.5.0-SNAPSHOT
SAML 2.0.0
VillagerOptimiser 1.1.1
EntityTrackerFixer
AntiAttackRL

**Comment by roughanddai** [comment]
also happend when suffocated in a wall

**Comment by CraftG** [comment]
Join our discord and get the latest dev build.
