### ISSUE TITLE
[Bug] Verbose turned off, still getting notification spammed

### ISSUE THREAD

**Issue by BrendanLeeT** [CraftG/Horizon#15]
Please describe the problem in detail and provide as much information as possible.

INFOMATION:
Server: PaperSpigot
Server version: 1.8.8

ISSUE TYPE: Bug

Extra Information:
Verbose turned off but still getting spammed in the chat

**Comment by CraftG** [comment]
did you give players the 'horizon.notify' permission? If yes, try to revoke the permission.

**Comment by CraftG** [comment]
I haven't meet this problem, but I tried to fix it. If you still have this problem, please reopen this issue.
