### ISSUE TITLE
[FP] Speed and Fly (Piston)

### ISSUE THREAD

**Issue by True-cc** [CraftG/Horizon#16]
Please describe the problem in detail and provide as much information as possible.

INFOMATION:
Server: CraftBukkit version git-Spigot (MC: 1.8.8)
Server version: CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Plugins (24): Atlas, AutoRestart, BanAnimations, ChestCommands, Citizens, CommandNPC, CommandSpy, ConditionalCommands, CratesPlus, Essentials, FastAsyncWorldEdit, HideAndCustomPlugins, HolographicDisplays, Horizon, LuckPerms, Multiverse-Core, PlugMan, ProtocolLib, Sentinel, SkinsRestorer, UUIDSpoof-Fix, ViaVersion, WorldEdit, WorldEditSelectionVisualizer

I NEVER DID /reload OR /plugman reload

bypass/false positive/bug/error/suggestion
ISSUE TYPE: false positive

If reporting a console error.
SERVER LOG: 

If reporting a false positive.
HORIZON LOG: https://www.mediafire.com/file/dm9dzk5uwdubpg9/2019-05-07.log/file

If reporting a false positive/bypass. (If possible)
VIDEO: https://youtu.be/Bz2Ea4pq05I

If reporting a bypass.
CLIENT:

**Comment by True-cc** [comment]
Sry I put it on mediafire. Paste bin was down at the time I made this. :/

**Comment by CraftG** [comment]
Sry the piston false positives can't be fixed in short time. It may get fix in future updates.
