### ISSUE TITLE
[Critical] Anti fly : "Expect" prevents users from using ladders

### ISSUE THREAD

**Issue by Ferocimo** [CraftG/Horizon#19]
INFOMATION:
Server: git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Server version: 1.13.2

bypass/false positive/bug/error/suggestion
ISSUE TYPE: FALSE POSITIVE/BUG

If reporting a false positive.
HORIZON LOG: Player XXXXX failed FLY Type:Expect t:stable, d:0.11760000228882461 VL:19.2 (+2.4) Ping:0

Hello,

We can't use ladders with your plugin, it detects it as flying. That makes the anti-fly feature, which is a key feature, entirely unusable. 

Thank you for looking into this as soon as possible.

**Comment by CraftG** [comment]
Fixed.
