### ISSUE TITLE
Slow-fall effect considered as flying

### ISSUE THREAD

**Issue by Ferocimo** [CraftG/Horizon#20]
INFOMATION:
Server: git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Server version: 1.13.2

bypass/false positive/bug/error/suggestion
ISSUE TYPE: FALSE POSITIVE/BUG

Hello,

If you are under the effect of slow falling, every time you fall from the slightest distance will be considered as flying (Expect) and will stuck you to the ground immediately. This makes this potion unusable with anti-fly feature.

**Comment by CraftG** [comment]
Fixed
