### ISSUE TITLE
Spawning on the roof of rooms when teleporting inside them

### ISSUE THREAD

**Issue by Ferocimo** [CraftG/Horizon#25]
INFOMATION:
Server: git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Server version: 1.13.2

bypass/false positive/bug/error/suggestion
ISSUE TYPE: BUG

Hello,

Thank you for fixing the previous issues reported. 
It seems that, when the plugin is active and you try to teleport to a home, warp, or anything that is placed in a small room (with a roof approximatively three blocks above the teleportation point), you will spawn on top of the room instead of inside it. It doesn't show any actual log though. 

For instance, using MobArena, teleporting into an arena lobby which has a roof three blocks above will teleport you on top of the roof.

**Comment by Ferocimo** [comment]
Do you think this will be fixed anytime soon ? As long as this issue is there we can't use your plugin.

**Comment by CraftG** [comment]
please try the latest version

**Comment by CraftG** [comment]
@Ferocimo tell me if it still happens.
