### ISSUE TITLE
Errors when killing mobs

### ISSUE THREAD

**Issue by Legolaszstudio** [CraftG/Horizon#28]
Every time a mob/player is killed I get this error, it has nothing to do with the server, it runs smooth. But it is annoying that the console gets spammed with these errors every time a mob is killed.

INFOMATION:
Server: Spigot
Server version: 1.12.2 latest

ISSUE TYPE: error

SERVER LOG: 
[https://pastebin.com/6jKzStAC](https://pastebin.com/6jKzStAC)

**Comment by CraftG** [comment]
I will fix it asap, thanks

**Comment by CraftG** [comment]
it seems you're not using the latest version. please try the latest version(1.2)
