### ISSUE TITLE
Warning spam (Netty related)

### ISSUE THREAD

**Issue by x04** [CraftG/Horizon#29]
Logs should give more information than I can, this warning spam has occurred every since I first started using Horizon.

INFOMATION:
Server: Paper
Server version: 1.14.1

bypass/false positive/bug/error/suggestion
ISSUE TYPE: Bug (warning spam)

If reporting a console error.
SERVER LOG: 
`[Mon, 27. May 2019 19:56:45 UTC WARN] java.lang.IllegalStateException: Tile is null, asynchronous access? CraftBlock{pos=BlockPosition{x=3080, y=84, z=280},type=CHEST,data=Block{minecraft:chest}[facing=west,type=left,waterlogged=false],fluid=net.minecraft.server.v1_14_R1.FluidTypeEmpty@3e2059ae}
[Mon, 27. May 2019 19:56:45 UTC WARN]     at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:28)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at org.bukkit.craftbukkit.v1_14_R1.block.CraftContainer.<init>(CraftContainer.java:13)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at org.bukkit.craftbukkit.v1_14_R1.block.CraftLootable.<init>(CraftLootable.java:17)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at org.bukkit.craftbukkit.v1_14_R1.block.CraftChest.<init>(CraftChest.java:19)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.getState0(CraftBlock.java:347)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.getState(CraftBlock.java:322)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.getState(CraftBlock.java:316)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at xyz.hstudio.horizon.nms.v1_14_R1.v1_14_R1.‎　‎　‎　꧅(aa:350)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at xyz.hstudio.horizon.check.iIIiIIIIIi.‎　꧅‎　(pm:715)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at xyz.hstudio.horizon.check.iIIiIIIIIi.‎　꧅‎　(pm:125)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at xyz.hstudio.horizon.check.CheckManager.‎　‎　‎　꧅(ag:113)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at xyz.hstudio.horizon.listener.v1_8.channelRead(qa:143)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:245)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[Mon, 27. May 2019 19:56:45 UTC WARN]     at java.lang.Thread.run(Thread.java:748)`

**Comment by CraftG** [comment]
Fixed.
