### ISSUE TITLE
Soul sand causes false-positive for flying (bubbly water)

### ISSUE THREAD

**Issue by x04** [CraftG/Horizon#30]
When a player tries to use a soul sand elevator (bubbly water bs) the "Expect" fly module flags them as flying and eventually results in them drowning due to not being able to go up the elevator.

INFOMATION:
Server: Paper
Server version: 1.14.1

bypass/false positive/bug/error/suggestion
ISSUE TYPE: false positive

If reporting a false positive.
HORIZON LOG: couldn't find this, but very easy to replicate.

**Comment by CraftG** [comment]
Fixed.
