### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by Pas02** [CraftG/Horizon#31]
Please describe the problem in detail and provide as much information as possible.

INFOMATION:
Server: (PaperSpigot/Spigot/Torch/...)
Server version: Spigot 1.8.8

bypass/false positive/bug/error/suggestion
ISSUE TYPE: error

If reporting a console error.
SERVER LOG:  https://pastebin.com/nHanDNhv
If reporting a false positive.
HORIZON LOG: -

If reporting a false positive/bypass. (If possible)
VIDEO: -

If reporting a bypass.
CLIENT: -

**Comment by CraftG** [comment]
Fixed.
