### ISSUE TITLE
False positive with FastBow

### ISSUE THREAD

**Issue by Ferocimo** [CraftG/Horizon#32]
INFOMATION:
Server: git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Server version: 1.13.2

bypass/false positive/bug/error/suggestion
ISSUE TYPE: FALSE POSITIVE

Hello,

With latest version, slightly charging bow and trying to fire that way will trigger FastBow and block the player from doing so.

**Comment by Ferocimo** [comment]
Same thing with Fast Eat / Fast Use.

**Comment by sachk** [comment]
Same here
