### ISSUE TITLE
Tons of false positive with Timer when the server freezes

### ISSUE THREAD

**Issue by Ferocimo** [CraftG/Horizon#34]
INFOMATION:
Server: git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Server version: 1.13.2

bypass/false positive/bug/error/suggestion
ISSUE TYPE: FALSE POSITIVE

Hello,

When there is a short freeze (like, for two seconds or so) on the server, every player is kicked for sending too many packets after a ton of false positives with Timer.

**Comment by 143mailliw** [comment]
Reproduced on 1.13
