### ISSUE TITLE
Error When Player Join

### ISSUE THREAD

**Issue by coco0325** [CraftG/Horizon#36]
Please describe the problem in detail and provide as much information as possible.

INFOMATION:
Server: PaperSpigot
Server version: 1.14.2

bypass/false positive/bug/error/suggestion
ISSUE TYPE: error

If reporting a console error.
SERVER LOG: 
02.06 21:06:39 [Server] ERROR Could not pass event PlayerJoinEvent to Horizon v1.3.2
02.06 21:06:39 [Server] INFO io.netty.channel.ChannelPipelineException: xyz.hstudio.horizon.listener.v1_8 is not a @Sharable handler, so can't be added or removed multiple times.
02.06 21:06:39 [Server] INFO at io.netty.channel.DefaultChannelPipeline.checkMultiplicity(DefaultChannelPipeline.java:625) ~[patched_1.14.2.jar:git-Paper-58]
02.06 21:06:39 [Server] INFO at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:318) ~[patched_1.14.2.jar:git-Paper-58]
02.06 21:06:39 [Server] INFO at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:308) ~[patched_1.14.2.jar:git-Paper-58]
02.06 21:06:39 [Server] INFO at com.comphenix.protocol.injector.netty.PipelineProxy.addAfter(PipelineProxy.java:54) ~[?:?]
02.06 21:06:39 [Server] INFO at xyz.hstudio.horizon.listener.v1_8.‎　꧅(xa:97) ~[?:?]
02.06 21:06:39 [Server] INFO at xyz.hstudio.horizon.listener.EventListener.‎　꧅(ja:121) ~[?:?]
02.06 21:06:39 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor45.execute(Unknown Source) ~[?:?]
02.06 21:06:39 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.2.jar:git-Paper-58]
02.06 21:06:39 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.2.jar:git-Paper-58]
02.06 21:06:39 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.2.jar:git-Paper-58]
02.06 21:06:39 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:534) ~[patched_1.14.2.jar:git-Paper-58]
02.06 21:06:39 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:191) ~[patched_1.14.2.jar:git-Paper-58]
02.06 21:06:39 [Server] INFO at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:169) ~[patched_1.14.2.jar:git-Paper-58]
02.06 21:06:39 [Server] INFO at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.14.2.jar:git-Paper-58]
02.06 21:06:39 [Server] INFO at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:255) ~[patched_1.14.2.jar:git-Paper-58]
02.06 21:06:39 [Server] INFO at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:129) ~[patched_1.14.2.jar:git-Paper-58]
02.06 21:06:39 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1201) ~[patched_1.14.2.jar:git-Paper-58]
02.06 21:06:39 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-58]
02.06 21:06:39 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-58]
02.06 21:06:39 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-58]
02.06 21:06:39 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

If reporting a false positive.
HORIZON LOG: 

If reporting a false positive/bypass. (If possible)
VIDEO: 

If reporting a bypass.
CLIENT:

**Comment by CraftG** [comment]
type /ver and send the output please

**Comment by coco0325** [comment]
git-Paper-58
