### ISSUE TITLE
Nofall false positive when player collides with player head

### ISSUE THREAD

**Issue by 143mailliw** [CraftG/Horizon#37]
Please describe the problem in detail and provide as much information as possible.

INFOMATION:
Server: (PaperSpigot/Spigot/Torch/...) Paper
Server version:  git-paper-58 1.14

bypass/false positive/bug/error/suggestion
ISSUE TYPE: false positive

If reporting a false positive.
HORIZON LOG: verbose info in video

If reporting a false positive/bypass. (If possible)
VIDEO: https://youtu.be/nN9jG5ol0D0

If reporting a bypass.
CLIENT:

**Comment by CraftG** [comment]
Thanks, I will fix it.
