### ISSUE TITLE
Horizon crash

### ISSUE THREAD

**Issue by BestMark** [CraftG/Horizon#38]
INFOMATION:
Server: Paper
Server version: 1.12.2
ProtocolSupport latest for 1.12.2

ISSUE TYPE: error

If reporting a console error.
SERVER LOG: https://pastebin.com/c86RkbJZ

**Comment by CraftG** [comment]
use the latest version of horizon please

**Comment by Flavourized** [comment]
That was a pretty fast response, so i'm gonna assume it was automated. 

My horizon version is Horizon-1.4.6-Hotfix#6
