### ISSUE TITLE
False positives with activated pistons

### ISSUE THREAD

**Issue by Ferocimo** [CraftG/Horizon#46]
INFOMATION:
Server: git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Server version: 1.13.2

bypass/false positive/bug/error/suggestion
ISSUE TYPE: FALSE POSITIVE

Hello,

If you try to get over an unactiveted piston, and then activate it so the head of the piston would normally push the player upward, you will get a ton of false positives with Fly (Expect) and Phase (Collision).

**Comment by CraftG** [comment]
known issue, it takes some time to fix it
