### ISSUE TITLE
False positives when mounting a creature

### ISSUE THREAD

**Issue by Ferocimo** [CraftG/Horizon#48]
INFOMATION:
Server: git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Server version: 1.13.2

bypass/false positive/bug/error/suggestion
ISSUE TYPE: FALSE POSITIVE

Hello,

There are many false positives when a player tries to mount a creature (Fly, Phase, Speed) when there are some blocks in the way. Example here :

http://www.noelshack.com/2019-23-7-1560089470-2019-06-09-16-10-44.png

In this configuration if the player tries to mount the golem (which is an NPC than can be mounted), false positives will occur.

**Comment by itsfoxbit** [comment]
Similar paper version on 1.13.2, having same problem. False positives when mounting.
