### ISSUE TITLE
[Bypass] Scaffold

### ISSUE THREAD

**Issue by MCMDEV** [CraftG/Horizon#53]
Please describe the problem in detail and provide as much information as possible.

INFOMATION:
Server: Spigot
Server version: 1.8.8

bypass/false positive/bug/error/suggestion
ISSUE TYPE: Bypass

If reporting a console error.
SERVER LOG: 

If reporting a false positive.
HORIZON LOG: 

If reporting a false positive/bypass. (If possible)
VIDEO: https://www.youtube.com/watch?v=AfR8YUTkW_Q

If reporting a bypass.
CLIENT: LiquidBpunce

**Comment by CraftG** [comment]
Join our discord and get the latest dev build.
