### ISSUE TITLE
Checks don't seem to work on 1.13.2 with 1.4.4

### ISSUE THREAD

**Issue by MithrandirCraft** [CraftG/Horizon#59]
The plugin doesn't seem to function (at least to the extent I tested to) on spigot 1.13.2's last build.
I tried fly and killaura hacks with Skillclient, on a clean spigot server with just Horizon, ProtocolLib, WorldEdit and Essentials installed.

Spigot 1.13.2
Horizon 1.4.4

**Comment by CraftG** [comment]
please provide more information

**Comment by MithrandirCraft** [comment]
Solved, was using OP lol.
