### ISSUE TITLE
Problem with a another plugin

### ISSUE THREAD

**Issue by DekoLP** [CraftG/Horizon#61]
Please describe the problem in detail and provide as much information as possible.

INFOMATION:
Server: PaperSpigot
Server version: 1.8.8

bypass/false positive/bug/error/suggestion
ISSUE TYPE: bug

Hello,

Im using a BedWars Plugin called "Modern BedWars" (https://www.spigotmc.org/resources/✖-modern-bedwars-like-german-server-1-8-1-9-1-10-1-11-1-12-✖.38619/)
The problem I have: Everytime I die ingame in bedwars I dont get spawned on the team spawn. I get spawned on the multiverse spawn. When I delete the AntiCheat its working fine again. What could be the problem for this?

**Comment by RBS0** [comment]
Also having this issue with MultiVerse
