### ISSUE TITLE
[FP] Any level of depth strider triggers speed check while moving in water

### ISSUE THREAD

**Issue by MithrandirCraft** [CraftG/Horizon#63]
Spigot 1.13.2
Horizon 1.4.5

Any level of depth strider equipment being applied to a player may probably cause rollbacks when swimming.

Very easy to reproduce.

![imagen](https://user-images.githubusercontent.com/6623704/60760797-c202f880-a03b-11e9-8e2f-f47b1f91a28d.png)

**Comment by Kars1090** [comment]
This happens to me too to the point where a player gets stuck at the bottom of the ocean and cant move until they take it off.
