### ISSUE TITLE
[False Positive] Movement

### ISSUE THREAD

**Issue by MithrandirCraft** [CraftG/Horizon#64]
Spigot 1.13.2
Horizon 1.4.5

Players easily get rolled back when running around.
This has been triggered by multiple legal, unequiped players throughout the server, in diferent moments. The rollback occurs without any console warnings...

This may be the worst false positive my players experience since it affects gameplay quite constantly.
I'll provide more details on this as I gather them if possible.

**Comment by CraftG** [comment]
Join our discord to get the latest dev build.
