### ISSUE TITLE
Using a bubble elevator causes rollbacks that cause the player to take fall damage until death

### ISSUE THREAD

**Issue by Kars1090** [CraftG/Horizon#67]
Please describe the problem in detail and provide as much information as possible.

INFOMATION:
Server: PaperSpigot
Server version: 1.13.2

ISSUE TYPE: 
bug

When using a bubble elevator, the player gets rolled back repeatedly to the bottom of the elevator. When they hit the bottom they take fall damage. The player is unable to free themselves from the elevator, because they can not reach the top. Basically using a bubblevator is a death sentence.

LOG:

> 20.07 17:33:37 [Server] INFO Horizon >> Verbose on!
> 20.07 17:33:45 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:0.5550000083446491 VL:3 (+3.0) Ping:74
> 20.07 17:33:45 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:0.5550000083446491 VL:6 (+3.0) Ping:74
> 20.07 17:33:45 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:0.5550000083446491 VL:9 (+3.0) Ping:74
> 20.07 17:33:45 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:0.5550000083446491 VL:12 (+3.0) Ping:74
> 20.07 17:33:45 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:15 (+3.0) Ping:74
> 20.07 17:33:45 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:18 (+3.0) Ping:74
> 20.07 17:33:45 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:21 (+3.0) Ping:74
> 20.07 17:33:45 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:24 (+3.0) Ping:74
> 20.07 17:33:46 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:27 (+3.0) Ping:74
> 20.07 17:33:46 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:30 (+3.0) Ping:74
> 20.07 17:33:46 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:33 (+3.0) Ping:74
> 20.07 17:33:46 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:36 (+3.0) Ping:74
> 20.07 17:33:46 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:39 (+3.0) Ping:74
> 20.07 17:33:46 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:42 (+3.0) Ping:74
> 20.07 17:33:46 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:45 (+3.0) Ping:74
> 20.07 17:33:46 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:48 (+3.0) Ping:74
> 20.07 17:33:46 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:51 (+3.0) Ping:74
> 20.07 17:33:47 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:0.5550000083446491 VL:54 (+3.0) Ping:74
> 20.07 17:33:47 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:57 (+3.0) Ping:74
> 20.07 17:33:47 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:0.5550000083446491 VL:60 (+3.0) Ping:74
> 20.07 17:33:48 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:63 (+3.0) Ping:74
> 20.07 17:33:48 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:66 (+3.0) Ping:74
> 20.07 17:33:49 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:0.5550000083446491 VL:69 (+3.0) Ping:74
> 20.07 17:33:49 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:72 (+3.0) Ping:74
> 20.07 17:33:49 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:75 (+3.0) Ping:74
> 20.07 17:33:49 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:78 (+3.0) Ping:74
> 20.07 17:33:49 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:81 (+3.0) Ping:74
> 20.07 17:33:49 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:84 (+3.0) Ping:74
> 20.07 17:33:49 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:87 (+3.0) Ping:74
> 20.07 17:33:50 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:0.5550000083446491 VL:90 (+3.0) Ping:74
> 20.07 17:33:50 [Server] INFO (H-INFO) | Horizon >> Kars_MC might be trying to fly
> 20.07 17:33:50 [Server] INFO Horizon >> The notification is sent.
> 20.07 17:33:50 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:0.5550000083446491 VL:93 (+3.0) Ping:74
> 20.07 17:33:50 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:96 (+3.0) Ping:74
> 20.07 17:33:51 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:99 (+3.0) Ping:74
> 20.07 17:33:51 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:102 (+3.0) Ping:74
> 20.07 17:33:51 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:0.5550000083446491 VL:105 (+3.0) Ping:74
> 20.07 17:33:51 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:108 (+3.0) Ping:74
> 20.07 17:33:51 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:111 (+3.0) Ping:74
> 20.07 17:33:52 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:114 (+3.0) Ping:74
> 20.07 17:33:52 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:0.45794504661239444 VL:117 (+3.0) Ping:74
> 20.07 17:33:52 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:120 (+3.0) Ping:74
> 20.07 17:33:52 [Server] INFO (H-INFO) | Horizon >> Kars_MC is suspicious of using Fly
> 20.07 17:33:52 [Server] INFO Horizon >> The notification is sent.
> 20.07 17:33:52 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:-0.3999999999999986 VL:123 (+3.0) Ping:74
> 20.07 17:33:53 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:0.5550000083446491 VL:126 (+3.0) Ping:74
> 20.07 17:33:54 [Server] INFO Horizon >> Player Kars_MC failed FLY Module:Equality d:0.435065347048635 VL:129 (+3.0) Ping:74
> 20.07 17:33:56 [Server] INFO Horizon >> Player Kars_MC failed TIMER Module:Analysis avg:41254911 VL:1 (+1.0) Ping:74
> 20.07 17:33:56 [Server] INFO Horizon >> Player Kars_MC failed TIMER Module:Analysis avg:44308168 VL:2 (+1.0) Ping:74
> 20.07 17:33:57 [Server] INFO Horizon >> Player Kars_MC failed TIMER Module:Analysis avg:47253889 VL:3 (+1.0) Ping:74

**Comment by CraftG** [comment]
Not sure if this is caused by horizon, but I can't reproduce it. I only got a few Speed(FastFall) false positives when using a bubble elevator. Can you use /hori verbose and upload the output?

**Comment by Kars1090** [comment]
> Not sure if this is caused by horizon, but I can't reproduce it. I only got a few Speed(FastFall) false positives when using a bubble elevator. Can you use /hori verbose and upload the output?

There are no other plugins on our server that affect movement. When drag down is disabled, you no longer die but when you take the elevator you get teleported back to before you entered. It is definitely Horizon.

I'm working on collecting the output. The server is hosted through an external party and the control panel confuses me so stand by for that.

**Comment by Kars1090** [comment]
Sorry for the delay. Here you go.

[Horizon bubble elevator.txt](https://github.com/CraftG/Horizon/files/3413759/Horizon.bubble.elevator.txt)
