### ISSUE TITLE
[False positive] Portal

### ISSUE THREAD

**Issue by Vyrezz** [CraftG/Horizon#72]
Please describe the problem in detail and provide as much information as possible.

INFOMATION:
Server: (PaperSpigot/Spigot/Torch/...)
Server version: Paper 1.14.4 Build 152

bypass/false positive/bug/error/suggestion
ISSUE TYPE: BUG

Description: Teleporting through a nether portal will take you to the nether, then instantly to the deep ocean. 

If reporting a console error.
SERVER LOG: NaN

If reporting a false positive.
HORIZON LOG: NaN

If reporting a false positive/bypass. (If possible)
VIDEO: NaN

If reporting a bypass.
CLIENT: NaN

**Comment by CraftG** [comment]
Fixed in the latest dev build.
