### ISSUE TITLE
[Error] Async command

### ISSUE THREAD

**Issue by Flavourized** [CraftG/Horizon#76]
Please describe the problem in detail and provide as much information as possible.

INFOMATION:
Server: Paper
Server version: 1.12.2 
Using Horizon-1.4.6-Hotfix#6

bypass/false positive/bug/error/suggestion
ISSUE TYPE: bug

IMAGE: http://prntscr.com/otm65j

Typed `/horizon help` and it crashed me. 
```
16.08 20:01:50 [Disconnect] User Flavour has disconnected, reason: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
```

**Comment by CraftG** [comment]
Probably because of the async incompatible of bungee. You can use Waterfall proxy to fix it.
Anyways, I will fix it in the next version.
