### ISSUE TITLE
Spam in console

### ISSUE THREAD

**Issue by klzxc99** [CraftG/Horizon#9]
INFOMATION:
Server: PaperSpigot
Server version: 1.12.2

ISSUE TYPE: spam in console
SERVER LOG: 05.04 18:09:29 [Server] INFO 	at xyz.hstudio.horizon.checks.q.🏹.🤐🙄﻿🙃(Unknown Source) ~[?:?]

**Comment by klzxc99** [comment]
![IMG](https://user-images.githubusercontent.com/47762903/55672510-7dcd5400-58a4-11e9-8341-977fb87bd077.PNG)

**Comment by CraftG** [comment]
try the latest version
